# State message for the MAV. Can be used for both true states and estimated

double pn   # north mav_position
double pe   # east mav_position
double h    # altitude
double phi
double theta
double psi
double Va   # airspeed
double alpha  # angle of attack
double beta   #sideslip angle
double p      #roll rate
double q      # pitch rate
double r      # yaw rate
double Vg     # ground speed
double gamma   #flight path angle
double chi      #course angle
double wn     # wind north
double we     # wind east
double bx     # gyro bias x
double by     # gyro bias y
double bz     # gyro bias z
