# State message for the MAV. Can be used for both true states and estimated
Header header
float32 pn   # north mav_position
float32 pe   # east mav_position
float32 h    # altitude
float32 phi
float32 theta
float32 psi
float32 Va   # airspeed
float32 alpha  # angle of attack
float32 beta   #sideslip angle
float32 p      #roll rate
float32 q      # pitch rate
float32 r      # yaw rate
float32 Vg     # ground speed
float32 gamma   #flight path angle
float32 chi      #course angle
float32 wn     # wind north
float32 we     # wind east
float32 bx
float32 by
float32 bz
